#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tensorboard
Version  : 0.1.4
Release  : 1
URL      : https://github.com/tensorflow/tensorboard/archive/0.1.4.tar.gz
Source0  : https://github.com/tensorflow/tensorboard/archive/0.1.4.tar.gz
Source1  : http://localhost/tensorflow/tensorflow_tensorboard-0.1.4-py3-none-any.whl
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : bazel openjdk-dev

%description
# TensorBoard ![Travis build status](https://travis-ci.org/tensorflow/tensorboard.svg?branch=master)

%prep
%setup -q -n tensorboard-0.1.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1503005760
bazel build tensorboard:tensorboard


%install
export SOURCE_DATE_EPOCH=1503005760
rm -rf %{buildroot}

%files
%defattr(-,root,root,-)
